name: ReleaseBuild-Local

on:
  workflow_call:  # Reusable by other workflows
  release:
    types: [created]
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo to ./source
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0  # Fetch all history for all branches and tags.

      - name: Checkout HL7/fhir-ig-history-template to ./history-template
        uses: actions/checkout@v3
        with:
          repository: HL7/fhir-ig-history-template
          path: history-template

      - name: Checkout WorldHealthOrganization/smart-html to ./webroot
        uses: actions/checkout@v3
        with:
          repository: WorldHealthOrganization/smart-html
          path: webroot
          fetch-depth: 0  # Fetch all history for all branches and tags.

      - name: Checkout FHIR/ig-registry to ./ig-registry
        uses: actions/checkout@v3
        with:
          repository: FHIR/ig-registry
          path: ig-registry

      - name: Setup publisher and install dependencies
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace hl7fhir/ig-publisher-base:latest /bin/sh -c "
            npm install -g fsh-sushi &&
            curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./publisher.jar --create-dirs
          "

      - name: Create package cache folder
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace hl7fhir/ig-publisher-base:latest /bin/sh -c "
            mkdir -p ./fhir-package-cache && chown 1001:127 ./fhir-package-cache
          "

      - name: Run the IG publisher
        run: |
          find . -type d
          docker run --rm -v $(pwd):/workspace -w /workspace hl7fhir/ig-publisher-base:latest java -Xmx4g -jar ./publisher.jar -ig source -package-cache-folder fhir-package-cache

      - name: Run publisher command for publishing release
        run: |
          find . -type d
          docker run --rm -v $(pwd):/workspace -w /workspace hl7fhir/ig-publisher-base:latest /bin/sh -c "
            ls -la /workspace/webroot &&
            java -Xmx4g -Dfile.encoding=UTF-8 -jar /workspace/publisher.jar -go-publish -package-cache-folder /workspace/fhir-package-cache -source /workspace/source -web /workspace/webroot -temp /workspace/temp -registry /workspace/ig-registry/fhir-ig-list.json -history /workspace/history-template -templates /workspace/webroot/templates
          "

      - name: Upload .zip files to release        
        run: |
          find ./release-assets -name "*.zip" -print0 | while IFS= read -r -d '' file; do
            encoded_file=$(echo "$file" | base64)
            echo "Uploading $(echo "$encoded_file" | base64 --decode) to release"
            gh release upload "v0.1.0a" -- "$(echo "$encoded_file" | base64 --decode)" --clobber
          done
#          docker run --rm -v $(pwd):/workspace -w /workspace hl7fhir/ig-publisher-base:latest java -Xmx4g -jar ./publisher.jar -go-publish -package-cache-folder $(pwd)/fhir-package-cache -ig . -source source -web $(pwd)/webroot -temp $(pwd)/temp -registry $(pwd)/ig-registry/fhir-ig-list.json -history $(pwd)/history-template -templates $(pwd)/webroot/templates

      - name: Exclude .zip files from gh-pages and move to release-assets
        run: |
          mkdir -p ./release-assets
          # Move all .zip files to release-assets
          find ./webroot/ig-build-zips -name "*.zip" -exec mv {} ./release-assets/ \;
          # Prepare the deploy folder excluding .zip files
          mkdir -p ./deploy
          rsync -av --exclude="*.zip" ./webroot/ ./deploy/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          destination_dir: sitepreview

      - name: Upload release assets (full-ig.zip and package.tgz)
        run: |
          mkdir -p ./release-assets
          mv ./source/output/package.tgz ./release-assets/

      - name: Upload .zip files to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find ./release-assets -name "*.zip" -print0 | while IFS= read -r -d '' file; do
            escaped_file=$(echo "$file" | sed 's/#/\\#/g')
            echo "Uploading $escaped_file to release"
            gh release upload "v0.1.0a" -- "$escaped_file" --clobber
          done


#            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber

      - name: Upload package.tgz to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release-assets/package.tgz
          asset_name: package.tgz
          asset_content_type: application/gzip
