# This workflow uses a remote action to do some repository actions like updating the readme files

name: CI

# Controls when the action will run. 
on:
  workflow_call: # Reusable by other workflows
  # Triggers the workflow on push or pull request events for any main branch
  push:
    branches-ignore:    
      - 'gh-pages'
  pull_request:
  
  workflow_dispatch:

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This action does nothing yet"
